Handle more commands in Spirc
plietar/librespot pull request #157
Opened 2017-03-05 08:03 UTC by joerg-krause

Add a handler for the commands: _Play, PlayPause, Pause, Prev, Next, VolumeUp_, and _VolumeDown_ to Spirc.

2017-03-06 15:42 UTC, plietar requested changes
Thanks, looks good overall.

Could you also add volume and load ?
```rust
impl Spirc {
  fn volume(&self, volume: u16) { ... }

  // device is the ident, not the name.
  // If device is None load on self
  fn load(device: Option<String>, tracks: Vec<SpotifyId>, track_index: usize, play: bool, position: u32) { ... }
}
```

For `load` we will want a way of discovering devices as well, but that can be added later

2017-03-06 15:42 UTC, plietar commented on src/spirc.rs
> +    pub fn playpause(&self) {
Put an underscore: `play_pause`

2017-03-06 15:42 UTC, plietar commented on src/spirc.rs
> +    pub fn volumeup(&self) {
`volume_up`

2017-03-06 15:42 UTC, plietar commented on src/spirc.rs
> +    pub fn volumedown(&self) {
`volume_down`

2017-03-06 15:42 UTC, plietar commented on src/spirc.rs
> +                // for boundaries and convert the new relative volume back to an absolute value.
Why does need to be converted to float ? You can just add 6554 as an integer (there's a small rounding error, but that's fine IMO)

2017-03-06 15:42 UTC, plietar commented on src/spirc.rs
> +                } else {
That should be `else if self.state.get_status() == PlayStatus::kPlayStatusPause`

2017-03-06 15:42 UTC, plietar commented on src/spirc.rs
> +    fn handle_play(&mut self) {
Add `assert_eq!(self.state.get_status(), PlayStatus::kPlayStatusPause)` and document it as a precondition

2017-03-06 15:42 UTC, plietar commented on src/spirc.rs
> +    fn handle_pause(&mut self) {
Add `assert_eq!(self.state.get_status(), PlayStatus::kPlayStatusPause)`

2017-03-06 15:42 UTC, plietar commented on src/spirc.rs
> +            if frame.get_typ() == MessageType::kMessageTypeNotify {
Not too comfortable with that, it'll start reacting to messages targeted at other devices.

I don't think we should send messages to ourselves. I suggest making `handle_command` do `if active { self.handle_play(); } else { broadcast_message(kMessageTypePlay); }`

2017-03-06 15:42 UTC, plietar commented on src/spirc.rs
> +                CommandSender::new(self, MessageType::kMessageTypePlay).send();
Broadcasting these messages isn't great, ideally we'd want to track the currently active device.
It's probably fine for now, we'll assume clients just ignore them if they aren't active.

Can you please add a TODO though.

2017-03-06 15:47 UTC, plietar commented
While you're at it, could you rename `CommandSender` to `MessageSender`, since command now refers to the `Spirc -> SpircTask`, and `handle_frame` to `handle_message`.

2017-03-06 15:51 UTC, plietar commented
I've never seen the `VolumeUp`/`VolumeDown`/`PlayPause` messages, which is why I've not bothered handling them.

Do you have a device which sends these ? I'm not objecting to implementing them, just curious.

2017-03-06 15:54 UTC, joerg-krause commented
> I've never seen the VolumeUp/VolumeDown/PlayPause messages, which is why I've not bothered handling them. Do you have a device which sends these ? I'm not objecting to implementing them, just curious.

I am using a device with some multimedia keys attached to GPIOs. So, my device is generating those commands, and the Spotify player gladly handles them.

2017-03-06 15:56 UTC, plietar commented
> I am using a device with some multimedia keys attached to GPIOs. So, my device is generating those commands, and the Spotify player gladly handles them.

So this is your code sending them right ? Seems like Spotify implemented them on the receiving side but none of their implementations actually send them.

2017-03-06 16:05 UTC, joerg-krause commented on src/spirc.rs
> +            if frame.get_typ() == MessageType::kMessageTypeNotify {
I'd like to use librespot with an Unix socket listener listening for commands generated by another process running on the same board. The other process handles input events like _PlayPause_. I don't want to have to instances of a librespot running, one for streaming and one for remote control, but only one librespot instance being capable of doing both. Note, that the size of a librespot binary is more than 2.1 MB and my device is limited in both flash and RAM memory.

2017-03-06 16:08 UTC, plietar commented on src/spirc.rs
> +            if frame.get_typ() == MessageType::kMessageTypeNotify {
I'm not arguing librespot shouldn't be able to control itself, just that there's no need to broadcast a message out.
If librespot is currently active we can just process the command locally.

2017-03-06 16:09 UTC, joerg-krause commented
Yes, I am using a Unix socket listener with librespot: https://github.com/joerg-krause/librespot/commit/3a03d21348e212235fc48a13cb3a5e30f356562a. The messages are generated by the running librespot instance.

2017-03-06 16:15 UTC, joerg-krause commented on src/spirc.rs
> +            if frame.get_typ() == MessageType::kMessageTypeNotify {
I see! I wasn't aware that these messages are broadcasted.

2017-03-06 16:16 UTC, joerg-krause commented on src/spirc.rs
> +                // for boundaries and convert the new relative volume back to an absolute value.
You're right! No need for float here...

2017-03-08 11:54 UTC, joerg-krause commented on src/spirc.rs
> +            if frame.get_typ() == MessageType::kMessageTypeNotify {
@plietar I've tested with the following code snippet:

``` Rust
fn handle_command(&mut self, cmd: SpircCommand) {
    SpircCommand::Pause => {
        if self.device.get_is_active() {
            self.handle_pause();
        } else {
             CommandSender::new(self, MessageType::kMessageTypePause).send();
        }
    }
}
```

librespot stops playback, but the Spotify Player is not notified about it. The Play/Pause button is still showing the pause icon and the progress bar for the seconds is still increasing.

So, these messages needs to be broadcasted so the Spotify Player is notified about the changes, right?

2017-03-08 12:43 UTC, plietar commented on src/spirc.rs
> +            if frame.get_typ() == MessageType::kMessageTypeNotify {
You only need to broadcast the `kMessageTypeNotify` using `self.notify(None);`, not the `kMessageTypePause`.

2017-03-08 13:16 UTC, joerg-krause commented on src/spirc.rs
> +            if frame.get_typ() == MessageType::kMessageTypeNotify {
Thanks! This works:

``` Rust
fn handle_command(&mut self, cmd: SpircCommand) {
        SpircCommand::Pause => {
        if self.device.get_is_active() {
            self.handle_pause();
        }
        self.notify(None);
    }
}
```

Should `self.notify(None);` better be placed inside the `if` branch`?

2017-03-08 15:03 UTC, joerg-krause commented
@plietar I've update the commit. I didn't not added `volume()` and `load()` yet, as i do not know how to pass the variables, e.g. `volume`, to `SpircTask`. But this can be done in a follow-up patch...

2017-03-09 18:25 UTC, mattiash commented
> Seems like Spotify implemented them on the receiving side but none of their implementations actually send them.

I have a Raumfeld One S which has a built-in spotify connect client and physical volume up/down buttons. If I play music with spotify connect and press those buttons, I can see the volume change in spotify. So it seems that the Raumfeld tells the spotify server that it has changed the volume.

I am very interested in this PR since I want to build something with similar functionality as the Raumfeld One S with a Raspberry PI, an external amplifier and a remote that allows me to change the volume and play/pause the music.

2017-03-16 13:36 UTC, plietar commented on src/spirc.rs
> +            SpircCommand::Play if active => {
This isn't handling the `!active` case anymore.
That code should look like 
```rust
match cmd {
    SpircCommand::Play => {
        if active {
            self.handle_play();
            self.notify(None);
        } else {
            CommandSender::new(self, MessageType::kMessageTypePlay).send();
        }
    }
```

2017-03-16 14:07 UTC, joerg-krause commented on src/spirc.rs
> +            SpircCommand::Play if active => {
For all commands (except Shutdown)?

2017-03-16 14:11 UTC, plietar commented on src/spirc.rs
> +            SpircCommand::Play if active => {
Yes, It's quite a lot of boilerplate unfortunately

2017-03-23 07:16 UTC, joerg-krause commented
@plietar I've updated the PR.

2017-03-26 11:53 UTC, plietar commented
Thanks to @herrernst travis is working again.
@joerg-krause could you rebase to get the fix please ?

2017-03-27 06:39 UTC, joerg-krause commented
@plietar Did the rebase, but travis is not running anymore?

2017-03-27 08:49 UTC, plietar approved these changes

2017-03-27 09:32 UTC, merged

2017-03-27 09:32 UTC, plietar commented
Thanks !

2017-03-28 19:54 UTC, cortegedusage commented
this might be a very ignorant question, 
but does this mean that librespot now can be controlled from the command line with someting simple as librespot play/pause/next?
or does this still involve some basic programming skills.

I'd like to control a playlist with a remote control that's why I'm asking.

2017-03-28 20:08 UTC, plietar commented
This is only an API applications which depend on librespot can use.
@joerg-krause exposes it as a Unix socket in his fork https://github.com/joerg-krause/librespot/commit/bc457711b54e0b6cde598e05f7876f2a528c807d

2017-03-28 20:27 UTC, cortegedusage commented
Thank you for your quick reply,
I'm afraid this is something way out of my league.
But as long as the music is playing, I can only bow my head in respect for
people who can code. 

keep up the good work!

2017-03-29 15:23 UTC, seanrand commented
@plietar would you consider making it possible to expose Spirc as a Unix socket, or do you think it's out of scope for librespot? I noticed that lots of refactoring happened between @joerg-krause's patch and current master, so my idea of simply hacking it into my local RPi instance of librespot is not as straight forward as i thought.

2017-03-29 16:08 UTC, joerg-krause commented
@seanrand Please have a look at my current https://github.com/joerg-krause/librespot/tree/tokio-uds branch, which is even with @plietar master branch, and adds a Unix domain socket.

I guess it is more a feature for https://github.com/Spotifyd/spotifyd.