Re-enable avahi support for discovery
plietar/librespot pull request #201
Opened 2017-06-15 22:30 UTC by awiouy

This pull request allows to select whether discovery is built based on mdns (by default) or on avahi.
I only streamlined Dockerfile and docker-build-avahi.sh.
Many thanks to @shanemeagher, who did the heavy lifting.

2017-06-20 03:06 UTC, awiouy commented
This works fine here: https://github.com/LibreELEC/LibreELEC.tv/pull/1622

2017-06-24 21:23 UTC, marcelveldt commented
you should probably extend the code some more because when one doesn't provide any of the discovery options, the code won't build. If you add a few checks more it will also build without any discovery, for example on windows.

e.g.:

#[cfg(any(feature = "with-rust-mdns", feature = "with-avahi"))]
use librespot::authentication::discovery::{discovery, DiscoveryStream};

2017-06-25 04:40 UTC, awiouy commented
Thanks for the heads-up @marcelveldt 
My Rust is too basic to do it myself, though.
If you create a commit in your github, I will add it to this pull request.
Thanks in advance.

2017-06-29 13:42 UTC, shanemeagher commented
@awiouy @marcelveldt I've updated my commits so that rust-mdns is used by default, even if `--no-default-features` is set. This keeps current behaviour for building librespot the same (also, my rust wasn't sufficient to build librespot with discovery disabled completely).

If someone want's to build librespot to use with avahi now, the `with-avahi` feature replaces rust-mdns with dns-sd.

I've also rebased on master and squashed it to one commit: https://github.com/shanemeagher/librespot/commit/6f515f42b7b9eb7ae3c896598cbf20bed769979f

2017-06-29 14:58 UTC, plietar requested changes
It seems to me like this would fail to build if both are enabled.

Instead it should pick one of the two, say the dns-sd one. You can use https://github.com/alexcrichton/cfg-if to make it easier

2017-06-29 14:58 UTC, plietar commented on Cargo.toml
> +default = ["portaudio-backend","with-rust-mdns"]
nit: there should be a space between the two items.

2017-06-29 14:58 UTC, plietar commented on Cargo.toml
> +with-rust-mdns = ["mdns"]
Could you rename the feature to `with-internal-mdns`

2017-06-29 14:58 UTC, plietar commented on Cargo.toml
> +with-avahi = ["dns-sd"]
Same, `with-external-mdns`.

`dns-sd` is actually Apple's API.
Avahi provides a compatibility layer between the two

2017-06-29 15:08 UTC, marcelveldt commented
If I may chime in too, I don't think it's a great idea that it will force one of the two with no-default-features, in my case for example I'm also compiling for Windows and I need to comment out the dns stuff. So better to specify both of them as a separate feature but pick one as the default. And off course the changes in the code that it will only load (the correct) dns/discovery code if the feature is actually enabled.

I'm really busy atm otherwise I would have provided the PR

2017-06-29 15:12 UTC, plietar commented
@marcelveldt currently if `--no-default-features` is used and neither is chosen explicitly, then it won't include any backend and build fine on Windows.

On the other hand, if both are enabled, it will fail to build, which is a problem to me

2017-08-03 14:56 UTC, shanemeagher commented
@plietar finally getting a chance to revisit this.

Have made most of your suggested changes but have a (probably simple) problem in `cargo.toml` where I currently have the following features:
```
with-internal-mdns  = ["mdns"]
with-external-mdns  = ["dns-sd"]
```
If neither is specified, cargo tries to build with `mdns` but as `mdns` is only specified by `with-internal-mdns`, it fails. I could add `with-internal-mdns` to the default features but if `--no-default-features` is used, it will still fail.

Any suggestions?

2017-08-03 18:59 UTC, plietar commented
@shanemeagher Did you use `#[cfg(mdns)]` around the `extern crate mdns` ?

2017-09-05 15:15 UTC, shanemeagher commented
@plietar I've started a new PR https://github.com/plietar/librespot/pull/246 to push the code directly. This should address all your comments above.

2017-09-06 06:17 UTC, awiouy commented
Feature taken over by #246. Closing.

2017-09-06 06:17 UTC, closed without merging