Add --disable-audio-cache startup parameter
plietar/librespot pull request #204
Opened 2017-06-20 10:32 UTC by michaelherger

Disable caching of downloaded audio files at runtime. Comes in handy when running librespot on a small device with SD card or other small storage.

2017-06-20 17:54 UTC, awiouy commented
Thanks! I am using this now, and I hope it will make it upstream.

2017-06-20 18:09 UTC, sashahilton00 commented
Using this now as well, +1 for upstream :)

2017-06-29 14:48 UTC, plietar commented
Thanks @michaelherger 

Could you move the logic to the `Cache::save_file` function ?

2017-06-29 15:07 UTC, mherger commented
I put it in the player code as I don't want to disable all (potential) file caching. It's really about caching the audio data. There could be other code using the cache. (FWICT there's none right now, is there?)

2017-06-29 15:13 UTC, plietar commented
Yes `save_file` is only for audio data, so it is fine to move it there

2017-06-29 15:18 UTC, michaelherger commented
Ok, will update my change.

(argh... at some point I have to have a better strategy to separate my pro from my personal GitHub account...)

2017-06-29 16:08 UTC, michaelherger commented
Hmm... credentials is using the same cache object all over the place. Not initializing cache for files only, but use it for credentials looks like a much more complicated change, dealing with multiple cache instances etc. Am I totally wrong?

2017-06-29 16:29 UTC, michaelherger commented
BTW: is cache/default_cache even used anywhere?

2017-06-29 17:26 UTC, plietar commented
My point was to make `use_audio_cache` a field of `Cache` rather than `Config`, and move the `if use_audio_cache` test into the `save_file` method.

`default_cache` is just some leftover from a previous implementation, I forgot to delete it. You can do it if you want

2017-06-29 19:23 UTC, michaelherger commented
Take 2.

2017-06-29 22:18 UTC, plietar requested changes

2017-06-29 22:18 UTC, plietar commented on src/main.rs
> +        Cache::new(PathBuf::from(cache_location), !matches.opt_present("disable-audio-cache"))
Just a nit, could you extract `!matches.opt_present("disable-audio-cache")` to a separate variable ?

2017-06-30 06:43 UTC, merged

2017-06-30 06:43 UTC, plietar commented
Awesome thanks !